name: Generate Dark Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"  # kör var 12:e timme

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate dark snake
        uses: Platane/snk@v3
        with:
          github_user_name: jennifermhansson   # <-- ändra om ditt namn skiljer sig
          outputs: |
            snake-dark.svg
          color_snake: "#39FF14"      # neon green
