name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"  # kör var 12:e timme
  workflow_dispatch:

jobs:
  build:
    name: generate snake
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate the snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: jennifermhansson   # <-- ändra till ditt användarnamn
          outputs: |
            dist/snake.svg

      - name: Push the snake.svg file to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
