name: Generate Snake Contribution Grid

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"  # kör var 12:e timme

jobs:
  generate:
    permissions:
      contents: write    # viktig! ger rätt att pusha
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: jennifermhansson   # <-- ändra om du heter annat
          outputs: |
            snake.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output         # filerna läggs här
          build_dir: .                 # sparas i root av output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
